name: Daily OFAC Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install
        run: pip install pandas requests

      - name: Run
        run: |
          wget https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/SDN_ADVANCED.ZIP
          unzip -o SDN_ADVANCED.ZIP
          python generate_ofac.py
          python generate_opensanctions.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 고정된 파일명만 덮어쓰기 및 추가
          git add ofac_sanctioned_addresses.csv 
          git add opensanctions_addresses.csv
          
          # 커밋 기록에만 업데이트 날짜 표시
          git commit -m "Update list $(date +'%Y%m%d')" || exit 0
          git push origin main --force
